### PR TITLE
created a typo on purpose

### PR DESCRIPTION
**Pull request by cdelcol**

### CODE REVIEW

**Comment by pelegri** [comment]
any reason not to close the request?

**Comment by cdelcol** [comment]
Sorry:) It was part of a devcon session that I did with Tim. Close away.
Cheers,

Chris

----- Original Message -----

**Comment by cdelcol** [comment]
Closed. Used for demonstration only.

**Comment by pelegri** [comment]
Thanks.

Sent from my BlackBerry PlayBook
www.blackberry.com

---

_From:_ "Chris DelCol (RIM)" <
reply@reply.github.com

> _To:_ "Eduardo Pelegri-Llopart" pelegri@calterra.com
> _Sent:_ March 21, 2012 6:54 AM
> _Subject:_ Re: [Alice] created a typo on purpose (#14)

Closed. Used for demonstration only. --- Reply to this email directly or
view it on GitHub:
https://github.com/blackberry/Alice/pull/14#issuecomment-4617636

**Pull request closed without merging**
